{% set version = "0.2.0" %}

package:
  name: reaktplot
  version: {{ version }}

source:
  url: https://github.com/reaktoro/reaktplot/archive/v{{ version }}.tar.gz
  sha256: 4481cca15643e5cdc7ec06f200c44714696c74b1dbbdad7d979f4a1441651e22

build:
  number: 0  
  skip: True  # [python_impl == 'pypy']

requirements:
  build:
    - {{ compiler('cxx') }}
    - catch2 =2
    - cmake
    - ninja

  host:
    - pip
    - plotly
    - pybind11
    - pybind11-abi
    - python
    - python-kaleido

  run:
    - plotly
    - pybind11
    - python
    - python-kaleido

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  files:
    - test/
  imports:
    - reaktplot

about:
  home: https://github.com/reaktoro/reaktplot
  summary: 'reaktplot is an easy-to-use C++ and Python plotting library powered by plotly.'
  description: |
    reaktplot is an easy-to-use C++ and Python plotting library powered by plotly.
    It has an intuitive interface and it works correctly even within Jupyter Notebooks!
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/reaktoro/reaktplot
  dev_url: https://github.com/reaktoro/reaktplot

extra:
  recipe-maintainers:
    - allanleal
