{% set version = "0.3.0" %}

package:
  name: reaktplot
  version: {{ version }}

source:
  url: https://github.com/reaktoro/reaktplot/archive/v{{ version }}.tar.gz
  sha256: 705e1f81a64f099498532b5eb0309dc0f522c23d1bff295fe45bd0900594a1d7

build:
  number: 1
  skip: true  # [python_impl == 'pypy']

requirements:
  build:
    - {{ compiler('cxx') }}
    - catch2 =2
    - cmake
    - ninja

  host:
    - pip
    - plotly
    - pybind11
    - pybind11-abi
    - python
    - python-kaleido

  run:
    - plotly
    - pybind11
    - python
    - python-kaleido

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  files:
    - test/
  imports:
    - reaktplot

about:
  home: https://github.com/reaktoro/reaktplot
  summary: reaktplot is an easy-to-use C++ and Python plotting library powered by plotly.
  description: |
    reaktplot is an easy-to-use C++ and Python plotting library powered by plotly.
    It has an intuitive interface and it works correctly even within Jupyter Notebooks!
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/reaktoro/reaktplot
  dev_url: https://github.com/reaktoro/reaktplot

extra:
  recipe-maintainers:
    - allanleal
